basePath & servers support; support more schema type
inaka/cowboy_swagger pull request #135
Opened 2021-07-22 08:58 UTC by DDDHuang

fixed: https://github.com/inaka/cowboy_swagger/issues/134

support more schema, as like open api 3.0.0:
```erlang
#{
        allOf => [
            #{
                type => object,
                required => [name],
                properties => #{
                    name => #{
                        type => string,
                        example => "exmaple"
                    }
                }
            },
            #{
                oneOf => [ cowboy_swagger:schema(<<"password_based">>)
                                 , cowboy_swagger:schema(<<"jwt">>)
                                 , cowboy_swagger:schema(<<"scram">>)
                ]    
            }
        ]
    },

```

2021-07-22 09:02 UTC, elbrujohalcon requested changes
Hi @DDDHuang. Thanks for the PR.
A few requests:

1. Can we use the full word `translate` instead of just `trans` when possible?
2. Can you add some tests?

2021-07-23 06:08 UTC, elbrujohalcon commented on src/cowboy_swagger.erl
> +    Url = maps:get(url, hd(Servers), <<"">>),
```suggestion
    [Server|_] = maps:get(servers, GlobalSpec, [#{}]),
    Url = maps:get(url, Server, <<"">>),
```

2021-07-23 06:11 UTC, elbrujohalcon requested changes
Two small ammendments.

2021-07-23 06:11 UTC, elbrujohalcon commented on src/cowboy_swagger.erl
> +    Url = maps:get(url, hd(Servers), <<"">>),
```suggestion
    [Server|_] = maps:get(servers, GlobalSpec, [#{}]),
    Url = maps:get(url, Server, <<"">>),
```

2021-07-23 06:11 UTC, elbrujohalcon commented on test/cowboy_swagger_SUITE.erl
> +  ok.
```suggestion
  {comment, ""}.
```
If your test case uses `ct:comment/1,2`, it must return `{comment, ""}` when it's successful.

2021-07-23 06:28 UTC, elbrujohalcon approved these changes

2021-07-23 06:28 UTC, merged

2021-07-23 06:31 UTC, elbrujohalcon commented
@DDDHuang Thanks! If you have any interest at all in becoming a maintainer of this repo, let me know and I can let you in. That way you'll be able to generate releases and publish them to hex.pm, among other things.

2021-07-23 06:50 UTC, DDDHuang commented
I'm happy to be the maintainer.

2021-07-23 06:56 UTC, elbrujohalcon commented
Well… as soon as you accept the invite, you'll be!
Ping me on slack if there is any issue.